##########################################################################
#basic inforamtion about experiment
##########################################################################
config: C:\Users\Machine Learning GPU\Desktop\fyp\fyp\new_method\config.yml
name: deblurring

##########################################################################
#update and display frequency
##########################################################################
display_step_freq: 5
save_step_freq: 1000
visualize_step_freq: 10
eval_step_freq: 100

##########################################################################
#about training and testing
##########################################################################
evaluate: false
sweep: true
test: false
train: false

##########################################################################
# data
##########################################################################
dataset: gopro
data_root_train: C:\Users\Machine Learning GPU\Desktop\GOPRO_Large_all(2)
seq_len_train: [4, 16]

training_augmentations:
  resize: [360, 512]

data_root_test: C:\Users\Machine Learning GPU\Desktop\GOPRO_Large_all(2)
seq_len_test: [4, 16]

test_augmentations:
  resize: [360, 512]

##########################################################################
# resume
##########################################################################
weights:

checkpoint_dir: C:\Users\Machine Learning GPU\Desktop\fyp\fyp\new_method\checkpoints\
run_dir: C:\Users\Machine Learning GPU\Desktop\fyp\fyp\new_method\runs\

##########################################################################
# data to tensorboard
##########################################################################
update_sweep_data: false
update_training_loss: true
update_validation_loss: true
update_weights: true

##########################################################################
# visualize
##########################################################################
visualize: true
visualization_path: C:\Users\Machine Learning GPU\Desktop\fyp\fyp\new_method\visualization\

##########################################################################
#optimizer and optimizer specific parameters
##########################################################################
optimizer:
  optimizer_name: AdamW
  weight_decay: 0.01
  eps: 1e-08

if_scheduler: false
scheduler: StepLR

##########################################################################
# hyperparameter sweep wandb format
##########################################################################
sweep_parameters:
  name: deblurring
  num_sweeps: 10
  gpus_per_trial: 1
  program: train.py
  method: bayes
  metric:
    goal: minimize
    name: test_mse
  parameters:
    lr:
      min: 0.0001
      max: 0.001
    batch_size:
      min: 2
      max: 8
      # step: 2
    epochs:
      min: 1
      max: 100
      # step: 2
    dropout:
      min: 0.0
      max: 0.8
    reconstruction_weight:
      min: 0.1
      max: 1.2
    laplacian_weight:
      min: 0.1
      max: 1.2
    grad_weight:
      min: 0.1
      max: 1.2
    ssim_weight:
      min: 0.1
      max: 1.2

##########################################################################
# training
##########################################################################
training_parameters:
  lr: 0.0001
  batch_size: 6
  num_epochs: 20
  prob_for_frame_drop: 0
  dropout: 0

##########################################################################
# testing
##########################################################################
testing_parameters:
  batch_size: 6

##########################################################################
# model and type of training
##########################################################################
num_workers: 4
mode: train_image_deblurring
# model parameters
model: blur_decoder

variational_gen:
  encoder:
    output_channels: 128

  positional:
    output_channels: 16

  latent:
    num_layers: 16
    output_channels: 256
    hidden_size: 256

attention_gen:
  sharp_encoder:
    output_channels: 128
    input_channels: 3
    nheads: 8

  blur_encoder:
    output_channels: 128
    input_channels: 3
    nheads: 8

  positional:
    output_channels: 16

  feature_forcasting:
    nheads: 8

  decoder:
    output_channels: 3
    input_channels: 128

blur_decoder:
  sharp_encoder:
    output_channels: 128
    input_channels: 3
    kernel_size: 3

  decoder:
    output_channels: 3
    input_channels: 128

  positional:
    output_channels: 16

  feature_predictor:
    nheads: 8
